name: Bug report
description: Report an issue with the project.

labels:
  - bug 🔥

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please do your best to fill out as much information as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please check if there is an existing bug report before creating a new issue. If you intend to submit a PR to fix this issue, let us know in the description.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: openapi-spec
    attributes:
      label: OpenAPI specification (optional)
      description: Please provide relevant part of your OpenAPI specification to recreate the issue.
      placeholder: OpenAPI Specification

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide your configuration file or CLI command used to recreate the issue.
      placeholder: openapi-ts -i path/to/openapi.json -o src/client

  - type: textarea
    id: system-info
    attributes:
      label: System information (optional)
      description: Please provide any relevant system information. This may include OS, browser, NPM version, Node.js version, etc.
      placeholder: System information
