name: Feature Request

description: Suggest a new feature for the project.

labels:
  - feature 🚀

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature! Please ensure your feature request has enough information so maintainers can decide if it will be worked on.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the proposed feature. The more information you can provide, the better.
      placeholder: Feature description
    validations:
      required: true
