name: unittest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Cache Modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run release

      - name: Run unit tests
        run: npm run test

      # - name: Run e2e tests
      #   run: npm run test:e2e

      # - name: Submit to Codecov
      #   run: npm run codecov

